"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

const key=(code:string)=>`zenkai-casino:${code}`;
export default function Home(){
  const router=useRouter(); const [error,setError]=useState(""); const [creating,setCreating]=useState(false);
  async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setCreating(true);setError(""); const f=new FormData(e.currentTarget); const body=Object.fromEntries(f.entries()); try{const r=await fetch('/api/rooms',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}); const d=await r.json(); if(!r.ok) throw new Error(d.error); localStorage.setItem(key(d.code),JSON.stringify({playerId:d.playerId,sessionToken:d.sessionToken})); router.push(`/room/${d.code}`);}catch(e:any){setError(e.message)}finally{setCreating(false)}}
  async function join(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError(""); const f=new FormData(e.currentTarget); const body=Object.fromEntries(f.entries()); try{const r=await fetch('/api/rooms/join',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}); const d=await r.json(); if(!r.ok) throw new Error(d.error); localStorage.setItem(key(d.code),JSON.stringify({playerId:d.playerId,sessionToken:d.sessionToken})); router.push(`/room/${d.code}`);}catch(e:any){setError(e.message)}}
  return <main className="shell"><section className="hero"><div className="brand">Maison de jeu RP</div><h1>ZENKAI CASINO</h1><p>Le hasard sourit parfois aux plus audacieux.</p><p className="muted">Ryôs fictifs uniquement — aucun argent réel, aucun retrait.</p></section>{error&&<div className="error">{error}</div>}<div className="grid two"><form className="panel" onSubmit={create}><h2>Créer une room</h2><label>Pseudo RP</label><input className="input" name="name" placeholder="Shuuto Nakae" required/><label>Jeu</label><select className="select" name="gameType" defaultValue="BLACKJACK"><option value="COINFLIP">Pile ou Face</option><option value="BLACKJACK">Blackjack</option><option value="POKER">Poker Texas Hold'em</option></select><div className="grid two"><div><label>Mise min</label><input className="input" type="number" name="minBet" defaultValue="100"/></div><div><label>Mise max</label><input className="input" type="number" name="maxBet" defaultValue="10000"/></div><div><label>Joueurs max</label><input className="input" type="number" name="maxPlayers" min="2" max="8" defaultValue="6"/></div><div><label>Solde de départ</label><input className="input" type="number" name="startingBalance" defaultValue="10000"/></div></div><br/><button className="btn" disabled={creating}>{creating?"Création…":"CRÉER LA ROOM"}</button></form><form className="panel" onSubmit={join}><h2>Rejoindre une room</h2><label>Pseudo RP</label><input className="input" name="name" required/><label>Code de room</label><input className="input" name="code" maxLength={8} placeholder="A7K9QX" required style={{textTransform:'uppercase'}}/><br/><button className="btn">REJOINDRE</button><hr style={{borderColor:'#34291f',margin:'24px 0'}}/><h3>Jeux disponibles</h3><p className="muted">Pile ou Face • Blackjack • Texas Hold'em</p><p className="muted">Rooms privées, journal RP, soldes virtuels et logique de jeu côté serveur.</p></form></div><div className="footer">Outil RP non officiel — monnaie virtuelle uniquement.</div></main>
}
