"use client";
import { useState } from "react";
import { CardView } from "./CardView";

export default function GamePanel({snap,me,act}:{snap:any;me:any;act:(action:string,payload?:any)=>Promise<void>}){
  const game=snap.game; const [bet,setBet]=useState(me.currentBet||snap.minBet); const [raise,setRaise]=useState(snap.minBet*2);
  if(!game||game.status!=="ACTIVE") return <div className="panel"><h2>Table</h2><p className="muted">Aucune partie en cours.</p><div className="row"><input className="input" style={{maxWidth:180}} type="number" value={bet} onChange={e=>setBet(+e.target.value)}/><button className="btn secondary" onClick={()=>act('SET_BET',{bet})}>Préparer {bet} Ryôs</button>{me.isHost&&<button className="btn" onClick={()=>act('START_GAME')}>COMMENCER</button>}</div><p className="muted">Mise autorisée : {snap.minBet} – {snap.maxBet} Ryôs.</p></div>;
  const s=game.state;
  if(s.kind==='COINFLIP'){
    const committed=s.commits?.[me.id]; const other=Object.entries(s.commits??{}).find(([id])=>id!==me.id)?.[1] as any; return <div className="panel"><h2>Pile ou Face</h2><div className="table"><div className="coin">{s.result??'RYÔ'}</div>{s.result?<h3>{s.result}</h3>:<p className="muted">{other?`Votre adversaire a choisi ${other.choice} pour ${other.bet} Ryôs.`:'Le premier joueur choisit une face et une mise.'}</p>}{!s.result&&!committed&&<><input className="input" style={{maxWidth:180}} type="number" value={bet} onChange={e=>setBet(+e.target.value)}/><div className="row"><button className="btn" onClick={()=>act('COIN_COMMIT',{bet,choice:'PILE'})}>PILE</button><button className="btn secondary" onClick={()=>act('COIN_COMMIT',{bet,choice:'FACE'})}>FACE</button></div></>}{committed&&!s.result&&<p className="ok">Choix verrouillé. En attente de l'autre joueur…</p>}</div></div>
  }
  if(s.kind==='BLACKJACK'){
    const h=s.hands?.[me.id]; const turn=s.order?.[s.turnIndex]===me.id; return <div className="panel"><h2>Blackjack</h2><div className="table"><div><div className="muted">Croupier</div><div className="cards">{s.dealer.map((c:string,i:number)=><CardView key={i} card={c}/>)}</div></div>{h?<div><div className="muted">Votre main — mise {h.bet} Ryôs</div><div className="cards">{h.cards.map((c:string,i:number)=><CardView key={i} card={c}/>)}</div><p>{h.status}</p></div>:<p className="muted">Vous ne participez pas à cette manche.</p>}{turn&&h?.status==='PLAYING'&&<div className="row"><button className="btn" onClick={()=>act('BLACKJACK',{move:'HIT'})}>TIRER</button><button className="btn secondary" onClick={()=>act('BLACKJACK',{move:'STAND'})}>RESTER</button><button className="btn secondary" onClick={()=>act('BLACKJACK',{move:'DOUBLE'})}>DOUBLER</button></div>}</div></div>
  }
  if(s.kind==='POKER'){
    const hole=s.hole?.[me.id]??[]; const seat=s.seats[s.currentIndex]; const turn=seat?.playerId===me.id && s.stage!=='SHOWDOWN'; const mine=s.seats.find((x:any)=>x.playerId===me.id); const call=Math.max(0,s.currentBet-(mine?.roundBet??0));
    return <div className="panel"><h2>Texas Hold'em</h2><div className="table"><div><div className="muted">Board — {s.stage}</div><div className="cards">{s.board.map((c:string,i:number)=><CardView key={i} card={c}/>)}</div></div><div className="stat"><span className="muted">Pot</span><strong>{s.pot} Ryôs</strong></div><div><div className="muted">Vos cartes</div><div className="cards">{hole.map((c:string,i:number)=><CardView key={i} card={c}/>)}</div></div>{s.winners?.length>0&&<p className="ok">{s.winners.map((w:any)=>`${snap.players.find((p:any)=>p.id===w.playerId)?.name}: +${w.amount} (${w.label})`).join(' • ')}</p>}{turn&&<div className="row"><button className="btn secondary" onClick={()=>act('POKER',{move:'FOLD'})}>FOLD</button>{call===0?<button className="btn" onClick={()=>act('POKER',{move:'CHECK'})}>CHECK</button>:<button className="btn" onClick={()=>act('POKER',{move:'CALL'})}>CALL {call}</button>}<input className="input" style={{maxWidth:130}} type="number" value={raise} onChange={e=>setRaise(+e.target.value)}/><button className="btn secondary" onClick={()=>act('POKER',{move:'RAISE',amount:raise})}>RAISE</button><button className="btn danger" onClick={()=>act('POKER',{move:'ALLIN'})}>ALL-IN</button></div>}</div></div>
  }
  return null;
}
