"use client";
import { use, useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import GamePanel from "@/components/GamePanel";

const storageKey=(code:string)=>`zenkai-casino:${code}`;
export default function RoomPage({params}:{params:Promise<{code:string}>}){
  const {code}=use(params); const router=useRouter(); const [session,setSession]=useState<any>(null); const [snap,setSnap]=useState<any>(null); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  useEffect(()=>{try{const s=JSON.parse(localStorage.getItem(storageKey(code))||'null'); if(!s) router.replace('/'); else setSession(s);}catch{router.replace('/')}},[code,router]);
  const load=useCallback(async()=>{if(!session)return; try{const r=await fetch(`/api/rooms/${code}?playerId=${encodeURIComponent(session.playerId)}&token=${encodeURIComponent(session.sessionToken)}`,{cache:'no-store'}); const d=await r.json(); if(!r.ok) throw new Error(d.error); setSnap(d); setError('');}catch(e:any){setError(e.message)}},[code,session]);
  useEffect(()=>{load(); const i=setInterval(load,1400); return()=>clearInterval(i)},[load]);
  async function act(action:string,payload:any={}){if(!session)return; setBusy(true);setError(''); try{const r=await fetch(`/api/rooms/${code}/action`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({playerId:session.playerId,sessionToken:session.sessionToken,action,payload})}); const d=await r.json(); if(!r.ok) throw new Error(d.error); await load();}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  const me=useMemo(()=>snap?.players?.find((p:any)=>p.id===session?.playerId),[snap,session]);
  if(!snap||!me) return <main className="shell"><div className="panel"><h2>Connexion à la table…</h2>{error&&<div className="error">{error}</div>}</div></main>;
  const gameName={COINFLIP:'Pile ou Face',BLACKJACK:'Blackjack',POKER:"Texas Hold'em"}[snap.gameType as string]??snap.gameType;
  const summary=snap.events.map((e:any)=>e.message).join('\n');
  return <main className="shell"><div className="roomTop"><div><div className="brand">ZENKAI CASINO</div><h1 style={{marginBottom:4}}>{gameName}</h1><div className="code">ROOM {snap.code}</div></div><div className="row"><button className="btn secondary" onClick={()=>navigator.clipboard.writeText(snap.code)}>Copier le code</button><button className="btn secondary" onClick={()=>navigator.clipboard.writeText(summary)}>Copier le résumé RP</button></div></div>{error&&<div className="error">{error}</div>}{busy&&<p className="muted">Action en cours…</p>}<div className="grid roomGrid"><div><GamePanel snap={snap} me={me} act={act}/>{me.isHost&&<div className="panel" style={{marginTop:18}}><h3>Contrôles de l'hôte</h3><div className="row"><button className="btn secondary" onClick={()=>act('LOCK',{locked:!snap.locked})}>{snap.locked?'Déverrouiller':'Verrouiller'}</button><button className="btn secondary" onClick={()=>act('RESET_BALANCES')}>Reset soldes</button><button className="btn danger" onClick={()=>act('CLOSE')}>Fermer la room</button></div></div>}</div><aside className="grid"><div className="panel"><h3>Joueurs</h3><div className="players">{snap.players.map((p:any)=><div className="player" key={p.id}><div><strong>{p.name}</strong> {p.isHost&&<span className="badge">HÔTE</span>}<div className="muted">Mise: {p.currentBet||0}</div></div><div style={{textAlign:'right'}}><div className="balance">{p.balance.toLocaleString('fr-FR')} Ryôs</div>{me.isHost&&!p.isHost&&snap.game?.status!=='ACTIVE'&&<button className="btn danger" style={{marginTop:6,padding:'5px 8px',fontSize:11}} onClick={()=>act('KICK',{playerId:p.id})}>Expulser</button>}</div></div>)}</div></div><div className="panel"><h3>Journal RP</h3><div className="events">{snap.events.map((e:any)=><div className="event" key={e.id}><time>{new Date(e.createdAt).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</time>{e.message}</div>)}</div></div></aside></div><div className="footer">Ryôs fictifs uniquement — aucun paiement, aucun retrait, aucune valeur réelle.</div></main>
}
